### ISSUE TITLE
🚀 Motivation 🚀

### ISSUE THREAD

**Issue by lilendian0x00** [goxray/tun#3]
Hey,
Just wanted to motivate and encourage you for making this wonderful program 🙏

You remind me of my old days and also motivate me to make creative things again.

Appreciate it much 💎

**Comment by godstanis** [comment]
Thanks, mate! Really appreciate it 🥹

Your xray-knife not only helped with some utils functions like config link parser, but also helped to understand xray core tooling better, so thank you very much! (I'm gonna add it to credits in README.md when I'm happy with the packages I built)

CLI version is the first step. I'm currently making the desktop version in go using fyne and this project package as foundation. It's gonna be available for macOS/Linux. I'm in late debugging/ui improvements phase, and I use it myself, so it's pretty solid at the moment. Going to upload it in a new repo soon.

It is basically done and works perfectly well, but I want to add some UI elements (like this upload/download chart I built today), and test it better. Here is a work in progress glimpse of the current state (the connection info to the right of the graph is actually directly parsed from your package 😸):

<img width="737" alt="image" src="https://github.com/user-attachments/assets/ef6ba1ad-7bd1-4efc-a29a-b6f4550bfda8" />

**Comment by lilendian0x00** [comment]
Of course mate 🤝

WOOOOOOW
I'm totally impressed by your project.

I'm also honored to see that someone benefiting from my program to create something truly useful and handy for society. 

I'll definitely keep track of your amazing project 🔥

**Comment by godstanis** [comment]
@lilendian0x00 I've published the GUI version, you can check it out in https://github.com/goxray/desktop
